build:
  image: bjodah/bjodahimg16:v1.2
  environment:
    - WITH_OPENMP=1
  commands:
    - python2 -m pip install --upgrade pip  # pip 8.1.1 has a bug
    - python3 -m pip install --upgrade pip  # pip 8.1.1 has a bug
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/ci.sh chemreac
    - CHEMREAC_INTEGRATION_KWARGS="dict(integrator='cvode')" ./scripts/ci.sh chemreac --slow --veryslow --cov chemreac --cov-report html
    - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - python2 setup.py sdist

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: chemreac
    source: deploy/
    target: ~
    recursive: true
    delete: false
