build:
  image: bjodah/bjodahimg:v1.1
  environment:
    - WITH_OPENMP=1
  commands:
    - pip install -r requirements.txt
    - pip3 install -r requirements.txt
    - ./scripts/ci.sh chemreac
    - CHEMREAC_SOLVER=sundials ./scripts/ci.sh chemreac --slow --veryslow
