build:
  image: bjodah/bjodahimg:v1.1
  environment:
    - WITH_OPENMP=1
  commands:
    - ./scripts/ci.sh chemreac
    - CHEMREAC_SOLVER=sundials ./scripts/ci.sh --slow --veryslow --cov chemreac --cov-report html
