build:
  image: bjodah/bjodahimg:v1.0
  environment:
    - WITH_OPENMP=1
    - CHEMREAC_SOLVER=sundials
    - CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/include/python2.7"
  commands:
    - pip install pyodeint pygslodeiv2
    - pip3 install pyodeint pygslodeiv2
    - PYTHONPATH=$(pwd) ./scripts/run_tests.sh
