dist: trusty
sudo: false
language: c
before_install:
  - wget --quiet http://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
install:
  - ./scripts/travis.sh /tmp/conda-recipe
script:
  - conda-build /tmp/conda-recipe
notifications:
  email: false
