language: python
python:
- '2.7'
- '3.4'
before_install:
- ./scripts/install_miniconda.sh 2.7 $HOME/miniconda
- ./scripts/conda_create_test-env.sh 2.7 $HOME/miniconda
- mv /home/travis/miniconda/envs/test-env/bin/../lib/libm.so* /tmp/
- ./scripts/aptget.ubuntu.12.04LTS.sh
- ./scripts/install_sundials_w_lapack.sh
install:
- source $HOME/miniconda/bin/activate test-env
- LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH DISTUTILS_DEBUG=1 python setup.py
  build_ext -i
script: LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH py.test --pep8 --doctest-modules
  --cov chemreac --cov-report html --ignore build/ --ignore setup.py
after_success:
- coveralls
- scripts/push-to-gh-pages.sh
notifications:
  email: false
env:
  global:
    secure: M+U3qO8QjKtvB9yNVlIiClqMbUsrEOoXSGDvvfI3gsKd2r+hpxjk2MoVcgf2b9Gvrt7vRWit1d6wEAwcNOhb/s/DpyWYR/Rz4rnmKe3iqnkSmad+jWPPjEN09uX1fgiewjxGl+Nx8XcCk0Dx0XR0S87UgTRkttA8Z43kYzJAvyc=
