package:
  name: chemreac
  version: "0.3.0.git"
  # the version being overridden by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

source:
  path: ../

requirements:
  build:
    - python
    - sundials
    - cython
    - numpy
    - pycompilation
    - pycodeexport
    - mako
  run:
    - python
    - numpy
    - scipy
    - sundials
    - matplotlib
    - future
    - sympy
    - quantities

test:
  requires:
    - pytest
    - sympy
    - quantities
    - periodictable
    - argh

about:
  home: https://github.com/chemreac/chemreac
  license: BSD License
