{% set name = "chemreac" %}
{% set version = "0.7.0+git" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19*  # [not win]
    - python
    - cython
    - numpy
    - sundials
    - mako
    - quantities
    - pycompilation
    - pycodeexport
    - block_diag_ilu
    - finitediff
    - pycvodes
    - chempy
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19*  # [not win]
    - python
    - cython
    - numpy
    - sundials
    - mako
    - quantities
    - pycompilation
    - pycodeexport
    - block_diag_ilu
    - finitediff
    - pycvodes
    - chempy

test:
  requires:
    - periodictable
    - argh
    - pytest
  imports:
    - chemreac
    - chemreac.util
  commands:
    - MPLBACKEND=Agg python -m pytest --pyargs chemreac

about:
  home: https://chemreac.github.io/
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python package for modelling chemical kinetics with diffusion and drift'
  doc_url: https://chemreac.github.io/docs/master/
  dev_url: https://github.com/chemreac/chemreac

extra:
  recipe-maintainers:
    - bjodah
