package:
  name: chemreac
  #  version: "x.y.z"
  # the version is actually being set by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

source:
  path: ../

requirements:
  build:
    - python
    - cython
    - numpy
    - patchelf
    - pycompilation
    - pycodeexport
    - mako
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - future
    - sympy

test:
  requires:
    - pytest
    - sympy
    - quantities
    - periodictable

about:
  home: https://github.com/bjodah/chemreac
  license: BSD License
